### ISSUE TITLE
VHDPlus terminal output is almost invisible in Dark and SuperDark themes

### ISSUE THREAD

**Issue by Andy2No** [leonbeier/VHDPlus_Libraries_and_Examples#5]
Apologies if this is the wrong repo for this issue, but I don't see one for the IDE.  If I open a new terminal and type a command, any response I get is in dark red / maroon text.  While using the Dark or SuperDark themes, this is unreadable, to me - it just doesn't have enough contrast to be clearly visible.

Is it possible to set the font colours used in the terminal?  Is there a way to make the fonts larger, both in the terminal and in the IDE in general?

Also, have you considered adding a Discussion tab to your repositories?  They're useful for non-urgent questions, such as this one, about design decisions which might not be considered bugs.   They're also a way for users of the repo to discuss it among themselves, and answer questions for each other, taking some of the load off yourselves.

**Comment by hendrikmennen** [comment]
The font colors are usually controlled by your OS. I guess you are using a linux distro? 
Can you tell me which one you are using?

**Comment by Andy2No** [comment]
@HendrikMennen I'm using it with Windows 7.  I have a custom theme, but I don't know where the dark red colour is being taken from.

The problem with them being taken from the OS settings is that to fix a problem with VHDPlus, I'd have to cause a problem with something else that currently works.

Also, the font sizes definitely aren't coming from my OS settings, even if the colours are.  I have fonts set to "Larger - 150%", but the fonts used in VHDPlus are really quite small.  I initially tried switching the display to 1080p, because the window didn't quite fit on the screen at its recommended 1360x768, but it was unreadable - everything was far too small for me to make it out.  It's manageable at 1360x768 but it would be better if I could set all the fonts to be larger, to make everything more easily readable.

**Comment by hendrikmennen** [comment]
Just the font colors for the terminal emulator are usually taken from the OS, in your case from Powershell. If you open Powershell on your OS, it should show the same colors in terminal right?

I will look later into the Font Scale issues, tbh I didn't experiment much with screens smaller than 1080p, and the normal Windows Scale works fine on Windows 10 or 11.

Btw, currently we usually use Discord for discussion and bug reporting.
You can join our server at https://vhdplus.com/discord

**Comment by hendrikmennen** [comment]
It is possible to change powershell colors for a session using commands.
I will create a solution for that later

**Comment by hendrikmennen** [comment]
It was indeed an issue with our code, I fixed it and it should be much better next update.
Thank you for the report.

**Comment by Andy2No** [comment]
Thanks.  I'm not seeing a change after the update I've just installed, but maybe that's not the one you mean.

FWIW, the dark red text I'm seeing turns out to be error messages - produced by typing commands that don't work the same in Powershell.  I can't set the error message colour in Powershell; I can only set the main text and background colours, and the pop up text and background colours, but none of those have an effect on the VHDPlus IDE.

The colours appear to be the defaults for Powershell, but not the ones I can set in its Properties.  Never mind.  I'll leave it alone, for now.  I didn't have an immediate need to use the terminal - I was just trying it out.

Thanks for the invite to join Discord, but they insist on having my phone number to verify the account, and I'm just not going to give it to them.   I'm not a habitual phone user and too many people have it already.  I'm sure Discord is a prime target for hackers, so sooner or later it would be available to the wrong people.

**Comment by hendrikmennen** [comment]
If you installed 0.10.9.6 it should be improved, since the strength of all colors was multiplied by 0.5 to be better in light mode before. 

For me the difference is quite obvious.
0.10.9.5
![image](https://user-images.githubusercontent.com/25281882/198120754-6cd4bdcc-0a25-4720-8c33-2c618bcb8ffc.png)


0.10.9.6
![image](https://user-images.githubusercontent.com/25281882/198119385-9f8847a3-59bd-4e24-95e8-7d48f417380e.png)

Btw, you can increase font size of the editor (and output) by using CTRL + Mousewheel

**Comment by Andy2No** [comment]
I see.  Yes, I guess it is brighter.  I still can't read the red against a dark background, at the default zoom level, but Ctrl+mouse wheel helps.  Thanks.

**Comment by hendrikmennen** [comment]
![image](https://user-images.githubusercontent.com/25281882/198121801-8e1844d2-4546-432c-a035-b24130bd48c3.png)

Looks like VSCode uses a filter to make it even more bright. I will try to match VSCode terminal for the next update

**Comment by Andy2No** [comment]
Great.  Thanks.  I'll look out for it.

Maybe it's just my monitor, or my actual eyesight.  Perhaps I have more trouble distinguishing red on black than most people.  That last example is definitely better, but the red text is still a little blurred, for me, compared to the yellow.  It's manageable though.

**Comment by hendrikmennen** [comment]
![image](https://user-images.githubusercontent.com/25281882/198125517-c0e878fa-b586-476a-8280-41f50d9f2ba6.png)

I think thats the best I can do, it almost matches VSCode colors.
Thanks for letting me know about this, it's definetly better this way.

The text scaling issue is not fixable from my side, since it's an issue with our UI Framework Avalonia.
You can use the normal windows Scale to make everything bigger though.
